### ISSUE TITLE
Asking about the new series and readme update

### ISSUE THREAD

**Issue by dat-le-4** [benbrastmckie/.config#91] opened 2023-02-20 19:13 UTC
I recognized that you just uploaded the first video for the new series and I got very excited for it. Is this github repo updated like what is on the video. Because when I after pulling, my nvim is not functioning as expected.

**Comment by benbrastmckie** [comment] 2023-02-20 19:49
I have maintained the cheatsheet.md file, but am yet to revise the Readme. Sorry for the delay but should get to it soon. I'll close out this issue when I do. I'll add a note for now. Thanks for the reminder :)

**Comment by dat-le-4** [comment] 2023-02-22 15:32
Are you still updating the config because I still see a few errors when run nvim. 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/96510793/220671760-f29029e3-fd28-4561-bc5f-d0419b0cc095.png">

**Comment by benbrastmckie** [comment] 2023-02-22 20:41
The config is up-to-date. It's been working for me for months. I do add things from time to time but they're small.

Looks like the problem you're having is to do with the Yanky plugin... When did you last pull down changes/clone the config?

**Comment by dat-le-4** [comment] 2023-02-22 20:46
I just tried to pull again and the problem is still there.

**Comment by benbrastmckie** [comment] 2023-02-22 22:52
Maybe try turning off Yanky? You can comment it out in the plugins.lua file and comment out the yanky.lua config file in init.lua

I'll go over this stuff in the config videos that I'll make soon, but you can also review the old config videos to get some sense of what the protocol is.

**Comment by dat-le-4** [comment] 2023-02-23 02:06
yep that fixed the error though. but is there a way to fix the error without not using it?

**Comment by benbrastmckie** [comment] 2023-02-24 02:17
Definitely. I'm going to close this issue, but can you open a new issue with 'Yanky' in the title, stating what the problem is. Others may have similar problems and I want the solution to be easy to find.

**Closed** 2023-02-24 02:17 UTC
